name: Main CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose

  fixes:
    name: Run Clippy and Fix Formatting
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: rustup component add clippy
      - run: cargo clippy --fix --allow-dirty --allow-staged
      - run: cargo fmt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "(CI) Apply clippy and rustfmt fixes."
          title: "(CI) Clippy and formatting fixes."
          body: "This PR applies fixes suggested by `cargo clippy --fix` and `cargo fmt`."
          branch: "ci/auto-fixes"
          delete-branch: true
          labels: "automated,clippy"
